config/routes.rb
Rails.application.routes.draw do
  get 'welcome/aboutme'

  get 'welcome/blog'

  get 'welcome/tutorials'

  get 'welcome/aboutme'

  get 'welcome/portfolio'

  get '/portfolio', :to => 'welcome#portfolio', as: 'portfolio'
  get '/index', :to => 'welcome#index', as: 'index'
  get '/aboutme', :to => 'welcome#aboutme', as: 'aboutme'
  get '/tutorials', :to => 'welcome#tutorials', as: 'tutorials'
  get '/blog', :to => 'welcome#blog', as: 'blog'
  get '/contact', :to => 'welcome#contact', as: 'contact'

  root 'welcome#portfolio'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Piara Sandhu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/_navbar.html.erb
<div class="whole-page">
  <nav class="left-nav-bar">
    <div class="header">
      <p>PIARA  </p>
      <p>SANDHU</p>
    </div>

    <div class="sep-line"></div>

    <div class="list-items">
      <ul class="link-set">
        <li class="links"><%= link_to "Portfolio", portfolio_url %></li>
        <li class="links"><%= link_to "Tutorials", tutorials_url %></li>
        <li class="links"><%= link_to "Blog", blog_url %></li>
        <li class="links"><%= link_to "About Me", aboutme_url %></li>
      </ul>
    </div>

    <div class="sep-line"></div>

    <div class="image-bar">
      <%= link_to "https://github.com/piara108", :target => "_blank" do %>
        <%= image_tag("github-icon.png", :alt => "github", :class => "image") %>
      <% end %>

      <%= link_to "https://www.linkedin.com/in/piarasandhu", :target => "_blank" do %>
        <%= image_tag("linkedin-icon.png", :alt => "linkedin", :class => "image") %>
      <% end %>

      <%= link_to "mailto:piarasandhu108@gmail.com", :target => "_blank" do %>
        <%= image_tag("email-icon.png", :alt => "email", :class => "image") %>
      <% end %>

      <%= link_to "https://twitter.com/sikh_n_destroy", :target => "_blank" do %>
        <%= image_tag("twitter-icon.png", :alt => "twitter", :class => "image") %>
      <% end %>

      <%= link_to "http://stackexchange.com/users/3317568/piara-sandhu", :target => "_blank" do %>
        <%= image_tag("stackoverflow-icon.png", :alt => "stack", :class => "image") %>
      <% end %>
    </div>
  </nav>
</div>

app/views/welcome/aboutme.html.erb
<%= render 'navbar' %>

<div class="title-and-content">
  <div class="title-bar">
    <p class="page-title">About Me</p>
  </div>

  <div id="about-content">
    <div id="body-text">

      <div id="image-me">
        <%= image_tag("me-holding-starfish.jpg", :as =>"me-starfish", :class => "m'image") %>
      </div>

      <div id="text-box">
        <p>
          I am a web developer with a focus on Ruby on Rails and JavaScript.
          I graduated from Dev Bootcamp in 2015 where I learned Ruby, Rails,
          HTML/CSS and a little bit of JavaScript.  On my free time, I love
          to play with Java and Android Studio, where I have a couple of apps
          on the Google PlayStore. I have several Arduinos and Raspberry Pis
          languishing in my room while I try to find some worthwhile projects.
          I love the challenge of writing code, especially the little victories
          it provides.
        </p>

        <p>
          When I'm not writing code I love to travel the world and learn new
          languages. I know a bit of German and I'm currently learning
          French. I look forward to the next time when I can travel to France
          and the UK.
        </p>

        <p>
          I studied marine biology with an emphasise on tropical
          fisheries at U.C. Santa Cruz. I love to explore California
          with my friends and family, especially my native Bay Area. I'm
          always finding new places to see and things to do.
        </p>

        <p>
          I'm currently searching for an entry level web developer position
          where I get to work with a great team and learn new
          technologies. You can view my various profiles or contact me
          on the left
        </p>
      </div>
    </div>
  </div>
</div>

app/views/welcome/blog.html.erb
<%= render 'navbar' %>

<div class="title-and-content">
  <div class="title-bar">
    <p class="page-title">Blog</p>
  </div>

  <div id="blog-content">
    <div id="body-text">
      <p>Blogs coming soon...</p>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="whole-page">
  <nav class="left-nav-bar">
    <div class="header">
      <p>PIARA  </p>
      <p>SANDHU</p>
    </div>

    <div class="sep-line"></div>

    <div class="list-items">
      <ul>
        <li class="links"><%= link_to "Portfolio", portfolio_url %></li>
        <li class="links"><%= link_to "Tutorials", tutorials_url %></li>
        <li class="links"><%= link_to "Blog", blog_url %></li>
        <li class="links"><%= link_to "About Me", aboutme_url %></li>
      </ul>
    </div>

    <div class="sep-line"></div>

    <div class="image-bar">
      <a href="https://github.com/piara108"><%= image_tag("github-icon.png", :alt => "github", :class => "image") %></a>
      <a href="https://www.linkedin.com/in/piarasandhu"><%= image_tag("linkedin-icon.png", :alt => "linkedin", :class => "image") %></a>
      <a href="mailto:piarasandhu108@gmail.com"><%=  image_tag("email-icon.png", :alt => "email", :class => "image") %></a>
      <a href="https://twitter.com/sikh_n_destroy"><%= image_tag("twitter-icon.png", :alt => "twitter", :class => "image") %></a>
      <a href="http://stackexchange.com/users/3317568/piara-sandhu"><%= image_tag("stackoverflow-icon.png", :alt => "stack", :class => "image") %></a>
    </div>
  </nav>
</div>

<div class="title-and-content">
  <div class="title-bar">
    <p class="page-title">Portfolio</p>
  </div>

  <div class="body-content">
    <div class="body-text">
      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>
      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>
      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>
      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>
      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>
      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>
      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>
      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>
      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>
      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>
      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>
      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>
      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>
      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>
      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>
      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>
      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>
      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>
      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>
      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>

      <p>
        Content here....
      </p>
    </div>
  </div>
</div>

app/views/welcome/portfolio.html.erb
<%= render 'navbar' %>

<div class="title-and-content">
  <div class="title-bar">
    <p class="page-title">Portfolio</p>
  </div>

  <div id="portfolio-content">
    <div id="body-text">

      <a href="https://github.com/piara108/spare-change", target="_blank">
        <figure>
          <%= image_tag("spare-change.jpg", :alt => "spare-change", :class => "por-img") %>
          <!-- <figcaption>Spare Change</figcaption> -->
        </figure>
      </a>

      <a href="https://github.com/piara108/keiter", target="_blank">
        <figure>
          <%= image_tag("keiter.jpg", :alt => "keiter", :class => "por-img") %>
          <!-- <figcaption>Keiter</figcaption> -->
        </figure>
      </a>

      <a href="https://github.com/piara108/smell-of-water", target="_blank">
        <figure>
          <%= image_tag("smell-of-water.jpg", :alt => "smell-of-water", :class => "por-img") %>
          <!-- <figcaption>The Smell of Water</figcaption> -->
        </figure>
      </a>

      <a href="https://github.com/piara108/dark-and-stormy", target="_blank">
        <figure>
          <%= image_tag("dark-n-stormy.jpg", :alt => "dark-n-stormy", :class => "por-img") %>
          <!-- <figcaption>Dark and Stormy</figcaption> -->
        </figure>
      </a>

      <a href="https://github.com/piara108/animal-facts-app", target="_blank">
        <figure>
          <%= image_tag("animal-facts.jpg", :alt => "animal-facts", :class => "por-img") %>
          <!-- <figcaption>Animal Facts</figcaption> -->
        </figure>
      </a>

      <a href="https://github.com/piara108/signals-from-mars-app", target="_blank">
        <figure>
          <%= image_tag("signals-from-mars.jpg", :alt => "signals-from-mars", :class => "por-img") %>
          <!-- <figcaption>Signals from Mars</figcaption> -->
        </figure>
      </a>

    </div>
  </div>
</div>

app/views/welcome/resume.html.erb
<h1>Welcome to my resume</h1>
<p>This contains all of my schooling and work experience</p>

app/views/welcome/tutorials.html.erb
<%= render 'navbar' %>

<div class="title-and-content">
  <div class="title-bar">
    <p class="page-title">Tutorials</p>
  </div>

  <div id="tutorial-content">
    <div id="body-text">
      <p>Tutorials coming soon...</p>
    </div>
  </div>
</div>